(ns eu.stratuslab.cimi.server
  "Implementation of the ring application used to create the
   servlet instance for a web application container."
  (:require [cemerick.friend :as friend]
            [clojure.tools.logging :as log]
            [compojure.handler :as handler]
            [eu.stratuslab.authn.workflows.authn-workflows :as aw]
            [eu.stratuslab.cimi.db.cb.utils :as db-cb-utils]
            [eu.stratuslab.cimi.db.couchbase :as db-cb]
            [eu.stratuslab.cimi.db.dbops :as db]
            [eu.stratuslab.cimi.middleware.base-uri :refer [wrap-base-uri]]
            [eu.stratuslab.cimi.middleware.exception-handler :refer [wrap-exceptions]]
            [eu.stratuslab.cimi.routes :as routes]
            [metrics.core :refer [default-registry]]
            [metrics.jvm.core :refer [instrument-jvm]]
            [metrics.ring.expose :refer [expose-metrics-as-json]]
            [metrics.ring.instrument :refer [instrument]]
            [org.httpkit.server :refer [run-server]]
            [ring.middleware.json :refer [wrap-json-body
                                          wrap-json-response]]))

(defn set-dbops-value
  [cb-cfg-file]
  (-> cb-cfg-file
      (db-cb-utils/create-cb-client)
      (db-cb/create)
      (db/set-impl!)))

(defn- create-ring-handler
  "Creates a ring handler that wraps all of the service routes
   in the necessary ring middleware to handle authentication,
   header treatment, and message formatting."
  []
  (log/info "creating ring handler")

  (let [workflows (aw/get-workflows)]
    (if (empty? workflows)
      (log/warn "NO authn workflows configured"))

    (instrument-jvm default-registry)

    (-> (friend/authenticate (routes/get-main-routes)
                             {:allow-anon?         true
                              :login-uri           "/cimi/login"
                              :default-landing-uri "/cimi/webui"
                              :credential-fn       (constantly nil)
                              :workflows           workflows})
        ;(handler/site {:session {:store (couchbase-store cb-client)}})  FIXME: Update to general DB.
        (handler/site)
        (wrap-exceptions)
        (wrap-base-uri)
        (expose-metrics-as-json "/cimi/metrics" default-registry {:pretty-print? true})
        (wrap-json-body)
        (wrap-json-response {:pretty true :escape-non-ascii true})
        (instrument default-registry))))

(defn- start-container
  "Starts the http-kit container with the given ring application and
   on the given port.  Returns the function to be called to shutdown
   the http-kit container."
  [ring-app port]
  (log/info "starting the http-kit container on port" port)
  (run-server ring-app {:port port :ip "127.0.0.1"}))

(declare stop)

(defn- create-shutdown-hook
  [state]
  (proxy [Thread] [] (run [] (stop state))))

(defn register-shutdown-hook
  "This function registers a shutdown hook to close the database
   client cleanly and to shutdown the http-kit container when the
   JVM exits.  This only needs to be called in a context in which
   the stop function will not be explicitly called."
  [state]
  (let [hook (create-shutdown-hook state)]
    (.. (Runtime/getRuntime)
        (addShutdownHook hook))
    (log/info "registered shutdown hook")))

(defn start
  "Starts the CIMI server and returns a map with the application
   state containing the Couchbase client and the function to stop
   the http-kit container."
  [port cb-cfg-file]
  (set-dbops-value cb-cfg-file)
  (db/bootstrap)
  (let [stop-fn (-> (create-ring-handler)
                    (start-container port))]
    {:stop-fn stop-fn}))

(defn stop
  "Stops the http-kit container and shuts down the Couchbase
   client.  Takes the global state map generated by the start
   function as the argument."
  [{:keys [stop-fn]}]
  (log/info "shutting down database client")
  (db/close)
  (log/info "shutting down http-kit container")
  (if stop-fn
    (stop-fn)))
